# Generated by Django 2.2.6 on 2019-10-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_votess'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votess',
            field=models.IntegerField(default=0),
        ),
    ]
